#!/bin/sh
# chkconfig: 2345 20 80
# description: start midiSynth
   
start() {
    modprobe snd-bcm2835
    modprobe snd-usb-audio
    modprobe snd-seq-midi
    midiSynth hw:2,0,0 saw &
}
   
stop() {
    killall midiSynth
}
   
case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       ps aux | grep midiSynth
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac
   
exit 0