#!/bin/sh
# chkconfig: 2345 20 80
# description: start miniMidiOut
   
start() {
    modprobe snd-usb-audio
    modprobe snd-seq-midi
    amixer sset Master unmute
    amixer sset Master 100%
    amixer sset Speaker unmute
}
   
stop() {
    killall miniMidiOut
}
   
case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       ps aux | grep miniMidiOut
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac
   
exit 0