midiDevice      =   /dev/midi2
modus           =   saw
outputDeviceId  =   -1
bufferSize      =   16
fading          =   10
envelopeSamples =   16000
keypadDevice    =   /dev/input/event0
sampleRate      =   44100
