MINIMIDIOUT_VERSION = 1.0
MINIMIDIOUT_SITE = $(TOPDIR)/../miniMidiOut-src
MINIMIDIOUT_SITE_METHOD = local

MINIMIDIOUT_DEPENDENCIES = portaudio

MINIMIDIOUT_CONF_OPTS += \
    -DPORTAUDIO_INCLUDE_DIR=$(STAGING_DIR)/usr/include \
    -DPORTAUDIO_LIBRARY=$(STAGING_DIR)/usr/lib/libportaudio.so

$(eval $(cmake-package))
